function Write-Spooky {
    #Variables
    $A=' '
    $B='.'
    $C='\'
    $D='/'
    $E='`'
    $F="'"
    $G='-'
    $H='('
    $I=')'
    $J='|'
    $K=';'
    $L='_'
    $M=','
    $N='OO'
    $O=$B+$G
    $AA=$A*2
    $AB=$A*3
    $AC=$A*4
    $AD=$A*5
    $AE=$G*2
    $P=$AE+$F
    $Q=$AA+$F
    $AF=$G*5
    $AG=$B*2+$A+$C
    $AH="$B$AE$B"
    $AI=$AF+$B
    $AJ=$O+$B
    $AK=$M+$AI
    $AL="$F$G$F"
    $AM=$C+$A
    $AN=$A+$D
    $AO=$D+$A
    $AP=$AM+$C
    $AQ=$AO+$D
    $AR=$J+$A
    $AS=$J+$AA
    $AT=$AS+$A
    $AU=$AT*2
    $AV=$D+$AB
    $AX=$C+$D
    $AY=$D+$C
    $AZ=$E+$F
    $BB=$AB+$AR
    $BC=$A+$E
    $BD=$E+$P
    $BE=$AM+$AZ
    $BF=$F+$P
    $BG="$AZ$AA$AL$Q"
    $BH=$AC+$AR
    $BI=$AO+$AY
    $BJ=$AQ+$AP
    $BK=$AP+$AQ
    $BL=$C+$AQ
    $BM=$A+$BL
    $BN=$A+$BI
    $BO="$O$F$I"
    $BP="$H$A$N"
    $BQ=$BP+$F
    $BR=$AS+$J
    $BS="$AS$AR$BR"
    $BT="$AA$BO$AK"
    $R=$AA+$AJ
    $BU="$BQ$R$Q"
    $BV=$L+$I
    $BW="$C$BV$A$BR$C$BR"
    $BX="$AA$AM$BS"
    $BY="$BC$AF$F"
    $BZ=$AX+$AN
    $CA=$AM+$A
    $CB=$BN+$BH
    $CC=$BJ+$AB
    
    #Write
    $A+$AH*14
    $AO+$AG*14
    $AM+$AX+$BE*12+$BK
    $A+$BZ+$BD*12+$BZ
    $BN+$A*48+$BI
    $BJ+$AB+$Q+$A+$BO+$A*27+$M+$G*3+$B+$AB+$BJ
    $BK+$AA+$CA+$BP+$A+$I+$A*27+$AU+$BK
    $BM+$AC+$K+$AI+$C+$BT*2+$A+$AU+$BM
    $CB+$AJ+$AA+$AR+$BU*2+$AU+$BN
    $CC+$AR+$AL+$AN+$BV+($AV+$BS)*2+$AU+$BJ
    $BK+$BB+$AJ+$BC+$B+$A+$BW*2+$AS+$B+$F+$AB+$BK
    $BM+$BH+$AS+$CA+$J+$BX*2+$BD+$AD+$BL
    $CB+$BF+$AA+$AV+$BG+$AB+$BG+$AH+$AC+$BN
    $CC+$E+$G*6+$F+($AD+$BY)*2+$A+$BF+$A*4+$BJ
    $BK+$A*46+$BK
    $BM+$A*47+$BM
    $BN+$AH*12+$BI
    $BJ+$AG*12+$D+$AP
    $BE*14+$AN
    $A+$BD*14
}
